### ISSUE TITLE
Document CORS settings with docker

### ISSUE THREAD

**Issue by tacman** [riccox/meilisearch-ui#130]
I'm getting an error running my local server, though that server works with my PHP client, so I'm almost sure it's a CORS error.

I'm running with a simple docker setup:

```yaml
    meilisearch:
        image: getmeili/meilisearch:v1.10
        container_name: 'meilisearch'
        ports:
            - 7700:7700
        volumes:
            - ./.docker/meili/:/meili_data/
        environment:
#            - MEILI_MASTER_KEY=MeiliKey
            - MEILI_NO_ANALYTICS=true
            - MEILI_TASK_WEBHOOK_URL=http://localhost:8002/meili
```

Can you document how this is supposed to be configured so that the ui can access it?
