### ISSUE TITLE
Singleton mode not working

### ISSUE THREAD

**Issue by Alirexaa** [riccox/meilisearch-ui#165]
**Describe the bug**
Running UI using container in Singleton mode not working. It's like running the container without singleton mode.

**To Reproduce**

Use the following compose file and browse to `http://localhost:24900`

```yml
version: '3.7'  

services:  
  meilisearch:  
    image: docker.io/getmeili/meilisearch:v1.10
    environment:  
      MEILI_MASTER_KEY: 'your_master_key'
    ports:  
      - "7700:7700" 

  meilisearch-ui:  
    image: docker.io/riccoxie/meilisearch-ui:v0.9.4 
    ports:  
      - "24900:24900"
    environment:  
      VITE_SINGLETON_HOST: "http://meilisearch:7700"  
      VITE_SINGLETON_API_KEY: 'your_master_key'
      VITE_SINGLETON_MODE: "true"
    depends_on:  
      - meilisearch  
```

**Expected behavior**
browse to http://localhost:24900 should show the Meilisearch instance page instead of first page.

**Screenshots**
We see this page when browsing to `http://localhost:24900`
![Capture](https://github.com/user-attachments/assets/cef7c0c9-8def-4222-bdc9-fa0aebf3a2ec)

**Environments (please complete the following information):**
 - OS: windows
 - Browser: chrome
 - Version : 0.9.4
