### ISSUE TITLE
BASE_PATH  inoperative?

### ISSUE THREAD

**Issue by Xuzan9396** [riccox/meilisearch-ui#182]
docker-compose.yaml

```
  meilisearch-ui:
    image: riccoxie/meilisearch-ui:latest # 使用 Meilisearch UI 镜像
    container_name: meilisearch-ui

    ports:
      - "24900:24900" # 映射前端应用的端口
    environment:
#      - MEILI_API_KEY=T5RRbg5VkE76H4o0 # 设置与 Meilisearch 相同的 API 密钥
      - MEILI_SERVER=http://meilisearch:7700 # 指定 Meilisearch 服务地址
      - BASE_PATH=/meilisearch

    depends_on:
      - meilisearch # 确保先启动 meilisearch 服务
    restart: unless-stopped # 配置自动重启策略
  ```
  
  
  
<img width="1010" alt="image" src="https://github.com/user-attachments/assets/5b321d23-72f6-40dd-b3dd-d9432d13eef1" />
<img width="760" alt="image" src="https://github.com/user-attachments/assets/34041268-f57c-4366-8fea-f655ea2ef540" />

Only available at http://localhost:24900/

A production environment, I need to visit https://xxxx.com/meilisearch, how to deal with, use nginx
