### ISSUE TITLE
Singleton mode always has connection failures

### ISSUE THREAD

**Issue by Skyppid** [riccox/meilisearch-ui#206]
**Describe the bug**
When I go to the UI in the browser I see my instance, it shows "running" and I can open an index. But basically every other action results in this screen:

![Image](https://github.com/user-attachments/assets/20bbdd3b-9906-4d2b-a1ab-b74571518024)

When I press reload I land at the entry site again. Makes it kind of useless to me.

We run this locally to verify our services work correctly and indexes are correctly created (mainly monitoring Meili).
Unfortunately the Readme lacks any information about how to set it up properly. We have a docker-compose.yaml file where I set the mentioned singleton environment variables. But seemingly this is not enough or the whole singleton mode is very buggy. There is unfortunately no other setup explained.

Ideally we want that the UI is already set up for our local development instance (not hosted anywhere), so every developer can just head to the defined URL and check it locally without need to add the instance manually.

**To Reproduce**
`docker compose up` using this configuration:
```yaml
  meiliSearch:
    image: getmeili/meilisearch:latest
    restart: unless-stopped
    ports:
      - 7700:7700
    environment:
      MEILI_MASTER_KEY: "123456789123456789"
    volumes:
      - meilisearch_data:/meili_data
    profiles:
      - all
      - e2e
      - endpoint
    healthcheck:
      test: set -o pipefail;curl -fsS http://host.docker.internal:7700/health | grep -q '{"status":"available"}'
      retries: 3
      timeout: 5s

  meiliSearch-UI:
    image: riccoxie/meilisearch-ui:latest
    restart: unless-stopped
    ports:
      - 24900:24900
    environment:
      VITE_SINGLETON_MODE: true
      VITE_SINGLETON_HOST: "http://host.docker.internal:7700"
      VITE_SINGLETON_API_KEY: "123456789123456789"
```

**Expected behavior**
Everything works fine.

**Screenshots**
See above.

**Environments (please complete the following information):**
 - OS: Windows (hosted in Linux container)
 - Browser: Firefox
 - Version: 0.11.5

**Comment by riccox** [comment]
Please see this [section](https://github.com/riccox/meilisearch-ui?tab=readme-ov-file#singleton-mode) and this [issue](https://github.com/riccox/meilisearch-ui/issues/43).

**Comment by riccox** [comment]
@Skyppid You used the `riccoxie/meilisearch-ui` docker image in your docker compose config, but you should pull the source & build this app by yourself by this [section](https://github.com/riccox/meilisearch-ui?tab=readme-ov-file#singleton-mode) if you wanna use singleton mode.

**Comment by MickLesk** [comment]
Hi, I am the maintainer of community-scripts ORG (https://github.com/community-scripts/ProxmoxVE) I have the same problem. I have been experimenting with it for a few hours, even if I set the singleton mode to false, I am always redirected to the warning page.

I am currently building the project in conjunction with Meilisearch as a bare-metal installation for ProxmoxVE. So it runs on the same machine. Here is an excerpt from the install file.

https://github.com/community-scripts/ProxmoxVED/blob/bbf24be3bfff1a281d537af32bfbd5c85f7e0d4f/install/meilisearch-install.sh#L36-L86

At first I had packed the .env in meilisearch_data as .env.ui, but this was not pulled in, so I then created the .env.local in meilisearch_ui (according to the readme). Unfortunately, no matter what I do, I always get the same error. Even if I set the singleton mode to false.

(Yes, I know it's optimized for Docker :smile:, but it's a normal pnpm/nodejs project after all :D) I also use Node22 and Debian 12 in this case.

---

**_(little side note):_**

I had to customize the vite.config.ts a lot, especially the git hashing. We pull the tarball/zipfile from the release, so all this is not “git pulled”. This ensures that we can neither install (pnpm build) nor start the project. (without this change)

```ts
// Plugin to get Git hash
function gitHashPlugin(): Plugin {
        return {
                name: “git-hash-plugin”,
                config: () => {
                        const hash = “unknown”; // Fixed value instead of Git command
                        return {
                                define: {
                                        __GIT_HASH__: JSON.stringify(hash),
                                },
                        };
                },
        };
}

**Comment by riccox** [comment]
@MickLesk Could you paste more info (ex: logs) to help me find out the problem, I can not reproduce.

**Comment by MickLesk** [comment]
yeah, i can do it in next 2 hours, currently i build another script, i give you asap feedback

**Comment by MickLesk** [comment]
Here my setup:
1. Meilisearch:
- Installed on /opt/meilisearch
- toml file located in /opt/meilisearch_data
- master_key set (PS: It doesn't matter that these are here, this is a rudimentary container that will be reset for issue creation anyway)  

<img width="602" alt="Image" src="https://github.com/user-attachments/assets/7c45d2c5-331d-4d36-af65-9fc992214e1b" />

Service run fine, meilisearch is available:

<img width="1117" alt="Image" src="https://github.com/user-attachments/assets/10fb5d32-9a44-454b-aed6-b69372c2d4e6" />


--- 

2. Meilisearch-UI
- Installed on /opt/meilisearch-ui
- optimized vite-config (git hash error below/above)
- located .env.local in the same folder (try with and without ") 

<img width="279" alt="Image" src="https://github.com/user-attachments/assets/114cd557-b7e4-4dc0-8b8e-076f0f2eeeb6" />

<img width="1398" alt="Image" src="https://github.com/user-attachments/assets/63bf94c5-747a-482f-8506-0af5cbaf4948" />

Service run fine too, website is available:

<img width="1019" alt="Image" src="https://github.com/user-attachments/assets/e6a2f28a-b928-4466-b13f-b00d2bd5e395" />

no more logs or issues in journalctl, do you have an static logfile? if yes, where?

<img width="1009" alt="Image" src="https://github.com/user-attachments/assets/590113c4-aeef-4d21-a50f-9e98a8ce680a" />



--- 
--- 

2nd issue with gitHash:
```bash
root@meilidev:/opt/meilisearch-ui# pnpm run start

> meilisearch-ui@0.11.5 start /opt/meilisearch-ui
> vite

`import sass from 'sass'` is deprecated.
Please use `import * as sass from 'sass'` instead.
print current base path undefined
/bin/sh: 1: git: not found
error when starting dev server:
Error: Command failed: git rev-parse HEAD
/bin/sh: 1: git: not found

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:882:11)
    at execSync (node:child_process:954:15)
    at config (file:///opt/meilisearch-ui/node_modules/.vite-temp/vite.config.ts.timestamp-1742463661288-42cf8d36cf0a9.mjs:148:20)
    at runConfigHook (file:///opt/meilisearch-ui/node_modules/.pnpm/vite@6.2.1_@types+node@22.13.10_jiti@2.3.3_sass@1.85.1_tsx@4.19.3_yaml@2.5.1/node_modules/vite/dist/node/chunks/dep-glQox-ep.js:54646:23)
    at async resolveConfig (file:///opt/meilisearch-ui/node_modules/.pnpm/vite@6.2.1_@types+node@22.13.10_jiti@2.3.3_sass@1.85.1_tsx@4.19.3_yaml@2.5.1/node_modules/vite/dist/node/chunks/dep-glQox-ep.js:53964:12)
    at async _createServer (file:///opt/meilisearch-ui/node_modules/.pnpm/vite@6.2.1_@types+node@22.13.10_jiti@2.3.3_sass@1.85.1_tsx@4.19.3_yaml@2.5.1/node_modules/vite/dist/node/chunks/dep-glQox-ep.js:43843:18)
    at async CAC.<anonymous> (file:///opt/meilisearch-ui/node_modules/.pnpm/vite@6.2.1_@types+node@22.13.10_jiti@2.3.3_sass@1.85.1_tsx@4.19.3_yaml@2.5.1/node_modules/vite/dist/node/cli.js:750:20)
 ELIFECYCLE  Command failed with exit code 1.
root@meilidev:/opt/meilisearch-ui# 
```

**Comment by riccox** [comment]
@MickLesk And browser debug log when error happened.

**Comment by fernvenue** [comment]
Same here.

**Comment by riccox** [comment]
For all concerned, you should not use the `riccoxie/meilisearch-ui` docker image if you wanna use singleton mode, but you should pull the source & build this app with your meilisearch instance config by yourself by following this [section](https://github.com/riccox/meilisearch-ui?tab=readme-ov-file#singleton-mode).

I can not reproduce this connection error you mentioned until now.

**Comment by Skyppid** [comment]
@riccox is there any specific reason why the docker image does not support that functionality? I hoped for something I throw into out dev docker-compose and be good with it. Having to compile it (I do not even have that stack on my machine as I'm a C# developer) manually kind of defeats any purpose of using it. Especially since we're multiple devs with very different setups.

Went with the non-singleton mode now and have to set it up again every time - annoying but less work than manually building it (and not being able to directly run it in docker, at least without additional work).

**Comment by riccox** [comment]
@Skyppid Working on a new approach to improve the experience of this part, will be launched soon.

But the problem in this issue should be caused by wrong usage of singleton mode.

**Comment by riccox** [comment]
For @Skyppid & all concerned, you can try latest version now,but wait for CI pls.
It gives a new approach to use new env variables to enable singleton mode with docker images.

**Comment by Skyppid** [comment]
@riccox Thanks! That helps a lot. I will test it out as soon as I can and give feedback :)

**Comment by fcosrno** [comment]
Thanks for all your work @riccox! Chiming in here with feedback on singleton with Docker. I can't reach the site when I go to http://localhost:4173/ with my browser. That's the correct url, right? Per the logs:

```
meilisearch-ui-1  | ♻️  Generating routes...
meilisearch-ui-1  | ✅ Processed routes in 214ms
meilisearch-ui-1  |   ➜  Local:   http://localhost:4173/
meilisearch-ui-1  |   ➜  Network: http://172.19.0.3:4173/
```

Here is my docker-compose.yaml. Am I missing something?

```
version: "3.8"

services:
  meilisearch:
    image: getmeili/meilisearch:v1.14.0
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_NO_ANALYTICS: true
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY}      
    volumes:
      - ./.data:/meili_data

  meilisearch-ui:  
    image: riccoxie/meilisearch-ui:latest
    ports:  
      - "24900:24900"
    environment:  
      SINGLETON_HOST: http://meilisearch:7700
      SINGLETON_API_KEY: ${MEILISEARCH_KEY}
      SINGLETON_MODE: true
    depends_on:  
      - meilisearch  

volumes:
  meili_data:
```

**Comment by riccox** [comment]
> Thanks for all your work [@riccox](https://github.com/riccox)! Chiming in here with feedback on singleton with Docker.
> 
> I can't reach the site when I go to http://localhost:4173/ with my browser. That's the correct url, right? Per the logs:
> 
> ```
> meilisearch-ui-1  | ♻️  Generating routes...
> meilisearch-ui-1  | ✅ Processed routes in 214ms
> meilisearch-ui-1  |   ➜  Local:   http://localhost:4173/
> meilisearch-ui-1  |   ➜  Network: http://172.19.0.3:4173/
> ```
> 
> Here is my docker-compose.yaml. Am I missing something?
> 
> ```
> version: "3.8"
> 
> services:
>   meilisearch:
>     image: getmeili/meilisearch:v1.14.0
>     container_name: meilisearch
>     ports:
>       - "7700:7700"
>     environment:
>       MEILI_NO_ANALYTICS: true
>       MEILI_MASTER_KEY: ${MEILISEARCH_KEY}      
>     volumes:
>       - ./.data:/meili_data
> 
>   meilisearch-ui:  
>     image: riccoxie/meilisearch-ui:latest
>     ports:  
>       - "24900:24900"
>     environment:  
>       SINGLETON_HOST: http://meilisearch:7700
>       SINGLETON_API_KEY: ${MEILISEARCH_KEY}
>       SINGLETON_MODE: true
>     depends_on:  
>       - meilisearch  
> 
> volumes:
>   meili_data:
> ```
> 
> I did notice at the top of the logs that `Custom base path:` is empty. Could that be an issue?
> 
> ```
> meilisearch-ui-1  | Singleton mode enabled
> meilisearch-ui-1  | Custom base path:
> meilisearch-ui-1  |
> meilisearch-ui-1  | > meilisearch-ui@0.12.1 build /opt/meilisearch-ui
> meilisearch-ui-1  | > vite build
> ```

@fcosrno Have you used the latest image? Try pull the latest version again or pull specified version image.

**Comment by riccox** [comment]
@fcosrno Fixed in latest version v0.12.2. Just enjoy it.

**Comment by fcosrno** [comment]
Works, thanks! For documentation, had to keep in mind this is a spa so I had to change the HOST:

```
  meilisearch-ui:  
    ...
    environment:  
      SINGLETON_HOST: http://meilisearch:7700
      SINGLETON_API_KEY: ${MEILISEARCH_KEY}
      SINGLETON_MODE: true
```

Heads up though: new problem. Upon opening in the browser the "stats" request is going nuts.

![Image](https://github.com/user-attachments/assets/16ef9553-9a01-4a9f-9f41-98d74adc3326)
