### ISSUE TITLE
@mantine/core: MantineProvider was not found in component tree, make sure you have it in your app

### ISSUE THREAD

**Issue by moda20** [riccox/meilisearch-ui#84]
**Describe the bug**
a Code bug, a package is not installed or something else is missing when accessing the indexes page only.

**To Reproduce**
run a local version of meilisearch on default settings and this repo on docker too. add the local instance and clikc on indexes. 
example compose servics used : 

```yaml

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.25.2
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    ports:
      - ${MEILI_PORT:-7700}:7700
    volumes:
      - ./data.ms:/data.ms
    restart: unless-stopped

  meilisearch_ui:
    container_name: meilisearch_ui
    image: riccoxie/meilisearch-ui:latest
    ports:
      - "8009:24900"
    restart: unless-stopped
```

**Expected behavior**
showing a list fo indexes
**Screenshots**
![image](https://github.com/riccox/meilisearch-ui/assets/23613485/22b938e4-e955-4d85-b7e0-cd4edc1926c9)

**Environments (please complete the following information):**
 - OS: [e.g. iOS] macOs 12.x
 - Browser [e.g. chrome, safari] Chrome 118
 - Version [e.g. 0.0.3] latest from docker hub as of the creation of this post
 
**Additional context**
the same issue is visible on the vercel hosted version fo meili search
